version: '3.8'
# without volumes
services:

  db:
    container_name: db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - ~/.postgres/app/:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    env_file:
      - ./.env

  backend:
    restart: always
    container_name: backend
    build:
      context: .
    volumes:
      - ~/.app/static/:/app/static/
      - ~/.app/media/:/app/media/
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - db
    command: > 
      bash -c "python3 manage.py collectstatic --noinput && python3 manage.py migrate  && gunicorn -b 0.0.0.0:8000 app.wsgi:application "


