# Generated by Django 4.0.8 on 2023-06-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Bachloar', 'Степень бакалавр'), ('Master', 'Степень магистра')], max_length=25, null=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First', 'Первый'), ('Second', 'Второй')], max_length=200, verbose_name='Семестр'),
        ),
    ]
