# Generated by Django 4.0.8 on 2023-06-07 20:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_choice_options_alter_essay_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Прогресс пользователя', 'verbose_name_plural': 'Записи прогресса пользователя'},
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Введите текст вопроса, который вы хотите отобразить', max_length=1000, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='random_order',
            field=models.BooleanField(default=False, help_text='Отображать вопросы в случайном порядке или как они заданы?', verbose_name='Случайный порядок'),
        ),
    ]
