# Generated by Django 4.0.8 on 2023-06-07 20:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Введите текст вопроса, который вы хотите отобразить', max_length=1000, verbose_name='Вопрос'),
        ),
    ]
