# Generated by Django 4.0.8 on 2023-06-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_question_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(help_text='Введите текст вопроса, который вы хотите отобразить', max_length=1000, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.CharField(blank=True, help_text='Объяснение, которое будет показано после ответа на вопрос.', max_length=2000, verbose_name='Объяснение'),
        ),
    ]
