# Generated by Django 4.0.8 on 2023-06-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_completedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
