# Generated by Django 4.0.8 on 2023-06-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_completedtask_created_at_delete_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtask',
            name='question',
        ),
        migrations.AddField(
            model_name='completedtask',
            name='count_solutions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
