# Generated by Django 4.0.8 on 2023-06-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_completedtask_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtask',
            name='is_completed',
        ),
    ]
