# Generated by Django 4.0.8 on 2023-06-25 18:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_alter_question_content_alter_quiz_exam_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Введите текст вопроса, который вы хотите отобразить', max_length=250000, verbose_name='Вопрос'),
        ),
    ]
