# Generated by Django 4.0.8 on 2023-06-05 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_newsandevents_id_alter_semester_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='posted_as',
            field=models.CharField(choices=[('Новость', 'Новость'), ('Событие', 'Событие')], max_length=10, verbose_name='Записать как:'),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='summary',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_current_semester',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Текущий семестр'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='next_semester_begins',
            field=models.DateField(blank=True, null=True, verbose_name='Начало следующего семестра'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(blank=True, choices=[('Первый', 'Первый'), ('Второй', 'Второй'), ('Третий', 'Третий')], max_length=10, verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.session', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_current_session',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Текущая сессия'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(max_length=200, unique=True, verbose_name='Сессия'),
        ),
    ]
