# Generated by Django 4.0.8 on 2023-06-07 23:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_newsandevents_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
