# Generated by Django 4.0.8 on 2023-06-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Бакалавр', 'Степень бакалавра'), ('Магистр', 'Степень магистра')], max_length=25, null=True),
        ),
    ]
