# Generated by Django 4.0.8 on 2023-06-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Bachloar', 'Степень бакалавра'), ('Master', 'Степень магистра')], max_length=25, null=True),
        ),
    ]
