# Generated by Django 4.0.8 on 2023-06-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hist_static',
            field=models.ImageField(blank=True, null=True, upload_to='hist_static/%y/%m/%d/'),
        ),
    ]
